name: PR Review Reminder

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR for Required Reviews
      uses: actions/github-script@v5
      with:
        script: |
          const prAuthor = github.context.payload.pull_request.user.login;
          const teamMembers = ['成員1的GitHub用戶名', '成員2的GitHub用戶名', '成員3的GitHub用戶名']; // 這裡換成你團隊所有成員的GitHub用戶名

          // 檢查PR創建者是否為團隊成員之一
          if (teamMembers.includes(prAuthor)) {
            core.setFailed(`PR作者 ${prAuthor} 不能自己審核自己的PR。`);
          } else {
            console.log(`PR創建者 ${prAuthor} 和審核者不同，允許進行。`);
